# frontend/Dockerfile.prod
# Строим production сборку React
FROM node:20 as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Переходим в Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

# Конфиг Nginx будет отдельно
COPY nginx.conf /etc/nginx/conf.d/default.conf
