# backend/Dockerfile.prod
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Production server через Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
